version: '3.3'
services:

  oled-container:
    image: oled-container-oled-container:latest
#   build:
#     context: ./
#     dockerfile: Dockerfile
    container_name: oled
    group_add:
      - "997"
      - "44"
    restart: unless-stopped
    devices:
      - /dev/i2c-1
      - /dev/vchiq
      - /dev/mem
      - /dev/gpiomem
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices:/sys/devices
      - /etc/udev/rules.d:/etc/udev/rules.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release
    network_mode: host

