version: '3.3'
services:

  oled-container:
    # image: oled-rakwireless:balena-run
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: oled
    devices:
      - "/dev/i2c-1"
      - "/dev/gpiochip0:/dev/gpiochip0"
    privileged: true
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    network_mode: host

